---  
- name: build www httpd directory tree
  hosts: yusur_197
  become: yes  
  become_method: sudo  
  vars_files:
    - vars/nest-vdpa-net-kernel_settings.yml

  tasks:  
    - name: Ensure "/home/hao/www/github/qemu" directory exists
      file:  
        path: "/home/hao/www/github/qemu"
        state: directory  
        mode: '0755'  
      delegate_to: localhost

    - name: Ensure /root/rpmbuild/SOURCES directory exists
      file:  
        path: /root/rpmbuild/SOURCES
        state: directory  
        mode: '0755'  
      delegate_to: localhost

    - name: Ensure "{{ build_dir }}/archive/" directory exists
      file:  
        path: "{{ build_dir }}/archive/"
        state: directory  
        mode: '0755'  
#########################################################################################
# Install Qemu
#########################################################################################

    # You can modify the qemu code, than tar it.
    - name: tar compress qemu source directory to /root/rpmbuild/SOURCES/qemu.tar.xz
#      command: tar czf /root/rpmbuild/SOURCES/qemu.tar.xz -C /home/hao/www/github   qemu
      command: tar czf /home/hao/www/archive/qemu.tar.xz -C /home/hao/www/github   qemu
      delegate_to: localhost

    - name: Download http://hao.vdpa.com/archive/qemu.tar.xz to /home/vdpa/archive/
      get_url:  
        url: http://hao.vdpa.com/archive/qemu.tar.xz
        dest: "{{ build_dir }}/archive/qemu.tar.xz"
        mode: '0644'
#        checksum: 'sha256:YOUR_CHECKSUM_HERE'  # Replace with the actual checksum    
#        timeout: 300  
        force: yes  # Force download even if file already exists

    - name: uncompress qemu.tar.xz
      command: tar xvf 

    - name: compile qemu
      command: ./configure --prefix=/usr --target-list=x86_64-softmmu

