# Playbook to set up a basic vdpa-net host on Fedora30
#
#
- hosts: kvm_host  
  remote_user: chenhao  # 替换为您的远程用户名  
  become: yes                 # 如果需要root权限  
  become_method: sudo        # 或者使用其他的提权方式  
  become_user: root          # 如果需要特定的用户来执行命令  
  vars_files:
    - vars/nest-vdpa-net-kernel_settings.yml
  tasks:
    - debug: 
        msg: Debug mode is enabled

# modify /etc/libvirt/qemu.conf user = "root", group = "root" and add
# cgroup_device_acl = [
#    "/dev/null", "/dev/full", "/dev/zero",
#    "/dev/random", "/dev/urandom",
#    "/dev/ptmx", "/dev/kvm",
#    "/dev/net/tun"
#]


# In order to run libvirt commands, we need to add the user to the
# libvirt group
    - name: Add user to libvirt group 
      user:
        groups:
          - libvirt
        name: "{{ ansible_facts['user_id'] }}"
        append: yes

    - name: Restart libvirtd
      service:
        name: libvirtd
        state: restarted

    - name: Destroy the guest L1-src VM (in case name colision)
      virt:
        name: "{{ guest_l1_src_name }}"
        state: destroyed
      ignore_errors: true
    
    - name: Destroy the guest L1-dst VM (in case name colision)
      virt:
        name: "{{ guest_l1_dst_name }}"
        state: destroyed
      ignore_errors: true

# Create and start the default network
    - name: Define vdpa default network
      virt_net:
        command: define
        name: vdpa-default
#        xml: "{{ lookup('file', 'vdpa-default-network.xml') }}"
        xml: "{{ lookup('file', 'vdpa-default-network.xml') }}"
    
    - name: Start vdpa default network
      virt_net:
        state: active
        name: vdpa-default
    - name: Start default network
      virt_net:
        state: active
        name: default

#==============================================================================
# Create the L1-src VM
# Before actually creating it, let's ensure there is no VM with the same name
# is already configured
#==============================================================================
    - name: Destroy the guest L1-src VM (in case name colision)
      virt:
        name: "{{ guest_l1_src_name }}"
        state: destroyed
      ignore_errors: true
    
    - name: Undefine guest L1-src vm (in case name colision)
      virt:
        command: undefine
        name: "{{ guest_l1_src_name }}"
      ignore_errors: true

    - name: Define the L1-src VM
      virt:
        command: define
        name: "{{ guest_l1_src_name}}"
        xml: "{{ lookup('template', 'nested_kernel_vdpa/nested-vdpa-net_guest_L1_src.xml.j2') }}"
        autostart: no

    - name: 加载tun模块
      modprobe:
        name: tun
        state: present

    - name: Start the L1-src VM
      virt:
        name: "{{ guest_l1_src_name}}"
        state: running
# virsh run as system permission
        uri: qemu:///system
      register: l1_src_vm_start_result
      become: yes

    - name: Get the IP address of the virtual machine L1-src
      shell: virsh domifaddr {{ guest_l1_src_name }}
      register: l1_src_vm_ip_result
      ignore_errors: yes

    - name: Display the IP address of the virtual machine L1-src
      debug:
        var: l1_src_vm_ip_result
      when: l1_src_vm_ip_result.rc == 0

    - debug: 
        msg: >
          "Now the Guest VM is running. To go inside the VM type
          virsh console {{ guest_l1_src_name }}"
    - debug: 
        msg: >
          "sshfs -o rw,allow_other root@10.2.20.56:/home/hao/nfs /mnt/nfs"

    - name: Wait for port 22 to become available on guest l1_src
      wait_for:
        host: "{{ guest_l1_src_ip }}"
        port: 22
        delay: 5    #每 5 秒检查一次端口 22 是否在 {{ guest_l1_src_ip }} 这个 IP 地址的主机上变得可用。


#==============================================================================
# Create the L1-dst VM
# Before actually creating it, let's ensure there is no VM with the same name
# is already configured
#==============================================================================
# Create the L1-dst VM
# Before actually creating it, let's ensure there is no VM with the same name
# is already configured
    - name: Destroy the guest L1-dst VM (in case name colision)
      virt:
        name: "{{ guest_l1_dst_name }}"
        state: destroyed
      ignore_errors: true
    
    - name: Undefine guest vm (in case name colision)
      virt:
        command: undefine
        name: "{{ guest_l1_dst_name }}"
      ignore_errors: true

    - name: Define the L1-dst VM
      virt:
        command: define
        name: "{{ guest_l1_dst_name}}"
        xml: "{{ lookup('template', 'nested_kernel_vdpa/nested-vdpa-net_guest_L1_dst.xml.j2') }}"
        autostart: no

    - name: Start the L1-dst VM
      virt:
        name: "{{ guest_l1_dst_name}}"
        state: running
        uri: qemu:///system
      register: l1_dst_vm_start_result

    - name: Get the IP address of the virtual machine L1-dst
      shell: virsh domifaddr {{ guest_l1_dst_name }}
      register: l1_dst_vm_ip_result
      ignore_errors: yes

    - name: Display the IP address of the virtual machine L1-dst
      debug:
        var: l1_dst_vm_ip_result
      when: l1_dst_vm_ip_result.rc == 0

    - debug: 
        msg: >
          "Now the Guest L1-dst VM is running. To go inside the L1-dst VM type
          virsh console {{ guest_l1_dst_name }}"

    - name: Wait for port 22 to become available on guest l1_dst
      wait_for:
        host: "{{ guest_l1_dst_ip }}"
        port: 22
        delay: 5    #每 5 秒检查一次端口 22 是否在 {{ guest_l1_dst_ip }} 这个 IP 地址的主机上变得可用。

    - name: Get the IP address of the virtual machine L1-dst
      shell: rm -f /home/hao/.ssh/known_hosts

#==============================================================================
# Playbook to run on L1-src to start up {{ guest_l2_name }}
#==============================================================================

# ssh L1-src
- hosts: l1_src
  remote_user: root  # 替换为您的远程用户名  
  become: yes                 # 如果需要root权限  
  become_method: sudo        # 或者使用其他的提权方式  
  become_user: root          # 如果需要特定的用户来执行命令  
  vars_files:
    - vars/nest-vdpa-net-kernel_settings.yml
  tasks:
    - debug: 
        msg: Debug mode is enabled

# sshfs mount source dir at /mnt/nfs
    - name: Ensure NFS mount point exists  
      file:  
        path: /mnt/nfs  
        state: directory  
        mode: '0755'  
  
    - name: Mount NFS share  
      mount:  
        path: /mnt/nfs  
        src: '10.2.20.56:/home/vdpa/'  
#       src: '10.2.20.56:/home/hao/www'  
        fstype: nfs  
#        opts: 'rw,allow_other'  
        opts: defaults
        state: mounted
      delegate_to: "{{ guest_l1_src_ip }}"  # 使用虚拟机的IP地址作为目标主机

    - name: Ensure /lib/modules/6.6.0/build symlink exists  
      file:  
        src: "/mnt/nfs/github/linux"  # 这是软链接指向的目标路径  
        dest: /lib/modules/6.6.0/build  # 这是软链接的路径  
        state: link  # 指定创建的是软链接

    - name: l1 src 加载tun模块
      modprobe:
        name: tun
        state: present
    - name: l1 src 加载kvm_intel模块
      modprobe:
        name: kvm_intel
        state: present

    - name: add /dev/vhost-vdpa0 device
      command: ./insmod.sh
#      command: ./insmod_origin.sh
      args:  
        chdir: /mnt/nfs/github/kernel_vdpa_driver
      ignore_errors: true

# Create the {{ guest_l2_name }} VM
# Before actually creating it, let's ensure there is no VM with the same name
# is already configured
    - name: Destroy the guest {{ guest_l2_name }} VM (in case name colision)
      virt:
        name: "{{ guest_l2_name }}"
        state: destroyed
      ignore_errors: true
    
    - name: Undefine guest {{ guest_l2_name }} vm (in case name colision)
      virt:
        command: undefine
        name: "{{ guest_l2_name }}"
      ignore_errors: true

    - name: Define the {{ guest_l2_name }} VM
      virt:
        command: define
        name: "{{ guest_l2_name }}"
        xml: "{{ lookup('template', 'nested_kernel_vdpa/nested-vdpa-net_guest_L2.xml.j2') }}"
        autostart: no

    - name: Edit the XML configuration of the virtual machine  
      command: virt-xml {{ guest_l2_name }} --edit --memorybacking locked=on          

    - name: Start the {{ guest_l2_name }} VM
      virt:
        name: "{{ guest_l2_name }}"
        state: running
# virsh run as system permission
        uri: qemu:///system
      register: l2_vm_start_result
      become: yes

    - name: Get the IP address of the virtual machine {{ guest_l2_name }}
      shell: virsh domifaddr {{ guest_l2_name }}
      register: l2_vm_ip_result
      ignore_errors: yes

    - name: Display the IP address of the virtual machine {{ guest_l2_name }}
      debug:
        var: l2_vm_ip_result
      when: l2_vm_ip_result.rc == 0

    - debug: 
        msg: >
          "Now the Guest VM is running. To go inside the VM type
          virsh console {{ guest_l2_name }}"


#==============================================================================
# playbook to run on l1-dst to set env
#==============================================================================

# ssh l1-dst
- hosts: l1_dst
  remote_user: root  # 替换为您的远程用户名  
  become: yes                 # 如果需要root权限  
  become_method: sudo        # 或者使用其他的提权方式  
  become_user: root          # 如果需要特定的用户来执行命令  
  vars_files:
    - vars/nest-vdpa-net-kernel_settings.yml
  tasks:
    - debug: 
        msg: debug mode is enabled

# sshfs mount source dir at /mnt/nfs
    - name: Ensure NFS mount point exists  
      file:  
        path: /mnt/nfs  
        state: directory  
        mode: '0755'  
  
    - name: Mount NFS share  
      mount:  
        path: /mnt/nfs  
        src: '10.2.20.56:/home/vdpa/'  
#        src: '10.2.20.56:/home/hao/www'  
        fstype: nfs  
#        opts: 'rw,allow_other'  
        opts: defaults
        state: mounted
      delegate_to: "{{ guest_l1_dst_ip }}"  # 使用虚拟机的IP地址作为目标主机

    - name: Ensure /lib/modules/6.6.0/build symlink exists  
      file:  
        src: "/mnt/nfs/github/linux"  # 这是软链接指向的目标路径  
        dest: /lib/modules/6.6.0/build  # 这是软链接的路径  
        state: link  # 指定创建的是软链接

    - name: l1 dst 加载tun模块
      modprobe:
        name: tun
        state: present
    - name: l1 dst 加载kvm_intel模块
      modprobe:
        name: kvm_intel
        state: present

    - name: add /dev/vhost-vdpa0 device
      command: ./insmod.sh
#      command: ./insmod_origin.sh
      args:  
        chdir: /mnt/nfs/github/kernel_vdpa_driver
      ignore_errors: true


#==============================================================================
# target host add tap to bridge
#==============================================================================

# ssh l1-dst
- hosts: kvm_host
  remote_user: root  # 替换为您的远程用户名  
  become: yes                 # 如果需要root权限  
  become_method: sudo        # 或者使用其他的提权方式  
  become_user: root          # 如果需要特定的用户来执行命令  
  vars_files:
    - vars/nest-vdpa-net-kernel_settings.yml
  tasks:
    - debug: 
        msg: debug mode is enabled
    - name: add tap0 to bridge
      command: brctl addif vdpabr0 tap0
    - name: add tap1 to bridge
      command: brctl addif vdpabr0 tap1
    - name: up tap0
      command: ifconfig tap0 up
    - name: up tap1
      command: ifconfig tap1 up
